services:
  - type: web
    name: ws-media-stream-server
    runtime: node
    nodeVersion: "20"
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
