services:
  - type: web
    name: ws-media-stream-server
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          name: ws-media-stream-server
          type: web
          property: port
